name: demo-actions

on:
  issues:
    types: opened
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Run a sample command
        run: echo "hello world"

      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: my-files
          path: ${{ github.workspace }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: my-files
          path: ${{ github.workspace }}